# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthApp_HCI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthApp_HCI
  pod 'KDCircularProgress'

end
